apiVersion: v2
name: booking-database-service
description: A Helm chart for booking-database-service in Kubernetes
type: application
version: 1.1.0
appVersion: latest
icon: "https://www.clipartmax.com/png/small/195-1955230_cloud-gateway-spring-cloud-contract-logo.png"
maintainers:
  - email: prabeen.soti@hotmail.com
    name: Prabeen Soti