apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
spec:
  {{ if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{ end }}
  selector:
    matchLabels:
      app: {{ include "service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "service.fullname" . }}
    spec:
      containers:
      - name: {{ include "service.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port | default 80 }}
        {{ if not .Values.health.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.health.readinessProbe.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.health.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.health.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.health.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.health.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.health.livenessProbe.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.health.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.health.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.health.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.health.livenessProbe.failureThreshold }}
        {{ end }}