apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app: booking-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: booking-service
  type: ClusterIP