apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-database-service
  labels:
    app: booking-database-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-database-service
  template:
    metadata:
      labels:
        app: booking-database-service
    spec:
      containers:
      - name: booking-database-service
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-mysqldb
              key: DATABASE_PASSWORD
        volumeMounts:
        - name: booking-mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: booking-mysql-volume
        persistentVolumeClaim:
          claimName: booking-mysql-pv-claim