apiVersion: v1
kind: PersistentVolume
metadata:
  name: booking-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi