apiVersion: v1
kind: Service
metadata: 
  name: booking-database-service
  labels:
    app: booking-database-service
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: booking-database-service