apiVersion: v1
kind: Service
metadata: 
  name: {{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port | default 80 }}
    protocol: {{ .Values.service.prtocal | default "TCP" }}
  selector:
    app: {{ include "service.fullname" . }}